kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build mint
  when:
    branch:
    - mint
  commands:
  - cd /mnt/website-mint
  - git pull
  - yarn install --frozen-lockfile
  - yarn build
- name: build mint testing
  when:
    branch:
    - mint-testing
  commands:
  - cd /mnt/website-mint-testing
  - git pull
  - yarn install --frozen-lockfile
  - yarn build
